export default [
  {
    job: 'work.job5',
    place: 'GRUPO COLBA',
    timeCount: 'work.date6',
    link: 'https://www.grupocolba.com.co/',
    img: 'img7',
  },
  {
    job: 'work.job4',
    place: 'Registradoras y equipos del caribe',
    timeCount: 'work.date5',
    link: 'https://empresite.eleconomistaamerica.co/REGISTRADORAS-EQUIPOS-CARIBE-SAS.html',
    img: 'img6',
  },
  {
    job: 'work.job3',
    place: 'Jezsy',
    timeCount: 'work.date2',
    link: 'https://www.linkedin.com/in/makinox/details/experience/',
    img: 'img5',
  },
  {
    job: 'work.job2',
    place: 'iSofact',
    timeCount: 'work.date4',
    link: 'https://www.isofact.com/',
    img: 'img4',
  },
  {
    job: 'work.job1',
    place: 'Soluntech',
    timeCount: 'work.date3',
    link: 'https://soluntech.com/',
    img: 'img3',
  },
  {
    job: 'work.job1',
    place: 'Crehana',
    timeCount: 'work.date2',
    link: 'https://www.crehana.com/',
    img: 'img2',
  },
  {
    job: 'work.job1',
    place: 'Eva',
    timeCount: 'work.date1',
    link: 'https://evacenter.com/',
    img: 'img1',
  },
];
