name: Integration

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  # # Set the job key. The key is displayed as the job name
  # # when a job name is not provided
  # super-lint:
  #   # Name the Job
  #   name: Lint code base
  #   # Set the type of machine to run on
  #   runs-on: ubuntu-latest
  #   steps:
  #     # Checks out a copy of your repository on the ubuntu-latest machine
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     # Runs the Integration action
  #     - name: Run Integration
  #       uses: github/super-linter@v3
  #       env:
  #         DEFAULT_BRANCH: main
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
