name: Testing & deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Running install process
        run: npm ci

      - name: Running building
        run: npm run build --if-present

      - name: Running tests
        run: npm test

      - name: Deploy to Firebase ${{ secrets.PROJECTNAME }}
        uses: doonstore/firebase-deploy@v1
        with:
          params: --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
